language: java
dist: trusty
cache:
  directories:
    - $HOME/.m2
services:
  - docker
script:
  - mvn clean package
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -f src/main/docker/Dockerfile.jvm -t "brunopacheco1/worms:jvm" .;
    else
    docker build -f src/main/docker/Dockerfile.jvm -t "brunopacheco1/worms:jvm-$TRAVIS_BRANCH" .;
    fi