version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: worms
      POSTGRES_PASSWORD: worms
      POSTGRES_DB: worms
  api:
    image: brunopacheco1/worms:native
    ports:
      - "5000:5000"
    depends_on:
      - database