version: '2'

services:
  postgres:
    image: postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: worms
      POSTGRES_PASSWORD: worms
      POSTGRES_DB: worms
  worms:
    image: brunopacheco1/worms:native
    ports:
      - "5000:5000"
    environment:
      DATABASE_JDBC: jdbc:postgresql://localhost:5555/worms 
